apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-test.fullname" . }}
  labels:
    {{- include "redis-test.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 6379
      protocol: TCP
      name: redis
  selector:
    {{- include "redis-test.selectorLabels" . | nindent 4 }}
